from __future__ import annotations

from typing import Optional, Protocol, Sequence

from backend.application.batch.batch_processor import BatchFileResult


class FileStorePort(Protocol):
    def store_file(self, data: bytes, filename: str, content_type: str) -> str: ...
    def get_file(self, file_id: str): ...
    def store_batch(self, results: Sequence[BatchFileResult], source: str) -> str: ...
    def get_batch(self, batch_id: str): ...
